server:
  port: 8222
spring:
  application:
    name: service-gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    gateway:
      routes:
        - id: service-hosp
          uri: lb://service-hosp
          predicates:
            - Path=/admin/user/**,/admin/hospset/**,/*/hosp/**,/*/dept/**,/*/sched/**

        - id: service-cmn
          uri: lb://service-cmn
          predicates:
            - Path=/*/cmn/**

        - id: service-user
          uri: lb://service-user
          predicates:
            - Path=/*/info/**,/user/weixi/**,/user/patient/**

        - id: service-sms
          uri: lb://service-sms
          predicates:
            - Path=/user/sms/**

        - id: service-oss
          uri: lb://service-oss
          predicates:
            - Path=/user/oss/**

        - id: service-order
          uri: lb://service-order
          predicates:
            - Path=/user/order/**,/order/weixi/**

        - id: service-statistics
          uri: lb://service-statistics
          predicates:
            - Path=/admin/statistics/**

        - id: service-gateway
          uri: lb://service-gateway
          predicates:
            - Path=/**
